### ISSUE TITLE
hipperfy

### ISSUE THREAD

**Issue by mphoward** [mphowardlab/hipper#3]
We should supply a script that can convert some of the easy CUDA or HIP calls to hipper calls. A first pass at this was implemented in this PR:

https://github.com/glotzerlab/hoomd-blue/pull/587

It's hard to replace all defines, thread ranks, etc. but we might be able to make educated guesses for some of them.

@schwendp Would you be willing to contribute your `replace.py` here? I can copy and modify it to be consistent with the new API? We should be able to automatically build your lookup table by scanning through the `docs/runtime.md` file.

**Comment by ghost** [comment]
I am definitely willing contribute my `replace.py`, but where exactly do you want it? It should already be apart of the files changed in [glotzerlab/hoomd-blue#587](https://github.com/glotzerlab/hoomd-blue/pull/587).

**Comment by mphoward** [comment]
Great, thanks! I think we should take `replace.py` and put it in `tools/hipperfy.py` here. Would you want to take a crack at a first PR, or would you like me to start and have you review it?

**Comment by ghost** [comment]
It would probably be best if you started. I can try my best to overlook though.

**Comment by mphoward** [comment]
I'm not planning to implement this unless there's a case where it's really necessary for performing large-scale conversions.
